name: Executar Bot de Sinais a cada 4 horas

on:
  schedule:
    - cron: "0 */4 * * *"  # Executa a cada 4 horas (00:00, 04:00, 08:00...)
  workflow_dispatch:  # Permite execução manual

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt || echo "Nenhuma dependência encontrada"

      - name: Configurar variáveis de ambiente
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> $GITHUB_ENV
          echo "CMC_API_KEY=${{ secrets.CMC_API_KEY }}" >> $GITHUB_ENV

      - name: Executar o bot
        run: python bot.py
